name: MobSlayerPlugin
version: 1.0
main: me.elmosahoe.mobslayerplugin.MobSlayerPlugin
author: Elmo
description: A plugin that assigns tasks to players to slay mobs.

commands:
  task:
    description: Assigns a new task based on the chosen difficulty.
    usage: /task <difficulty>
    permission: mobslayer.assign
  taskcheck:
    description: Checks your current task progress.
    usage: /taskcheck
    permission: mobslayer.check


